### ISSUE TITLE
[Bugs] Arch Linux 下运行错误

### ISSUE THREAD

**Issue by zxp19821005** [zengxiaolou/ecm#11]
如题。
版本：0.0.3
错误日志如下：
```
$ ./electronclipboardmanager 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@/components/singletons'
Require stack:
- /home/zxp-endeavouros/.cache/paru/clone/electronclipboardmanager-bin/src/opt/ElectronClipgbboardManager/resources/app.asar/app/build/pages/main_page/main.js
- /home/zxp-endeavouros/.cache/paru/clone/electronclipboardmanager-bin/src/opt/ElectronClipgbboardManager/resources/app.asar/app/build/index.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:116646)
    at Module._resolveFilename (/home/zxp-endeavouros/.cache/paru/clone/electronclipboardmanager-bin/src/opt/ElectronClipgbboardManager/resources/app.asar/node_modules/module-alias/index.js:49:29)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/electronclipboardmanager-bin/src/opt/ElectronClipgbboardManager/resources/app.asar/app/build/pages/main_page/main.js:47:20)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
```

**Comment by zengxiaolou** [comment]
Thank you for providing the error information. May I ask if you have run the 'yarn init:all' command? I have not been able to reproduce this issue on Ubuntu.

**Comment by zengxiaolou** [comment]
Thank you for your reminder. I have fixed the alias issue by replacing 'module-alias' with a Babel plugin. The tool still has many problems, but it does not affect its use. If you have any good suggestions, please let me know. Thank you.
